[project]
name = "mr-urdf-loader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Minchang Sung", email = "tjdalsckd@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "modern-robotics>=1.1.1",
    "numpy>=2.2.6",
    "urchin>=0.0.30",
]

[project.scripts]
mr-urdf-loader = "mr_urdf_loader:main"

[project.optional-dependencies]
pybullet = [
    "pybullet>=3.2.7",
]

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
